"""init tables

Revision ID: 6a08b774c016
Revises: 
Create Date: 2025-11-08 15:29:15.317741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a08b774c016'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_categoria'), 'pets', ['categoria'], unique=False)
    op.create_index(op.f('ix_pets_id'), 'pets', ['id'], unique=False)
    op.create_index(op.f('ix_pets_localizacao'), 'pets', ['localizacao'], unique=False)
    op.create_index(op.f('ix_pets_nome'), 'pets', ['nome'], unique=False)
    op.create_index(op.f('ix_pets_telefone'), 'pets', ['telefone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_telefone'), table_name='pets')
    op.drop_index(op.f('ix_pets_nome'), table_name='pets')
    op.drop_index(op.f('ix_pets_localizacao'), table_name='pets')
    op.drop_index(op.f('ix_pets_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_categoria'), table_name='pets')
    op.drop_table('pets')
    # ### end Alembic commands ###
